# Generated by Django 2.1.5 on 2021-04-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=6)),
                ('starttime', models.TimeField()),
                ('genre', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('person_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
